sudo: required

servies: docker

before_install:
  -docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exc --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec rails test